# Generated by Django 5.2.8 on 2025-12-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_recipes_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='products',
        ),
    ]
