# Generated by Django 5.2.8 on 2025-12-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_products_recipes_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'author')},
        ),
    ]
