# Generated by Django 5.2.8 on 2025-12-15 10:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_image_file_path),
        ),
    ]
